compute_environment: LOCAL_MACHINE
num_machines: 1
num_processes: 8
# deepspeed_config:
#   deepspeed_hostfile: /root/mpi_hostfile
distributed_type: MULTI_GPU
mixed_precision: bf16
machine_rank: 0  # 0表示这是第一台机器，1表示第二台，以此类推
main_process_ip: null  # 主节点的IP地址，如果是多节点训练，需要填写
main_process_port: null  # 主节点的端口，如果是多节点训练，需要填
main_training_function: main
main_process_port: 29500